[application]
name = "counter-mobile-app"
# Prioritize mobile platforms when building.
default_platform = "mobile"

[web.app]

# HTML title tag content
title = "counter-mobile-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
style = []
script = []

# Important configuration for Mobile
[mobile]
# Unique identifier on the Android Store or Android Phone
package_id = "com.vuduczuy.counter"
app_name = "CounterMobile"

[android]
architectures = ["aarch64", "armv7", "x86_64"]
min_sdk_version = 21
target_sdk_version = 33
# You can add permissions here if needed (example: internet)
build_features = ["viewBinding"]

[bundle]
# Information for packaging the app
identifier = "com.vuduczuy.counter"
publisher = "VuDucZuy"
icon = ["assets/favicon.ico"]
